# Generated by Django 4.1.3 on 2023-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('send_update', models.BooleanField(default=False)),
                ('photo', models.FileField(upload_to='profile')),
            ],
        ),
    ]
